name: Documentation

on:
  workflow_run:
    workflows: [ "Test and Release" ]
    branches: [ dev ]
    types:
      - completed

jobs:
  pre_job:
    name: Pre Job

    if: github.event_name == 'push'

    runs-on: ubuntu-latest

    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}

    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          github_token: ${{ github.token }}
          paths: '["docs/**"]'

  deploy:
    name: Deploy

    needs: pre_job

    if: needs.pre_job.outputs.should_skip != 'true'

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node-version: [ 12.x ]
      fail-fast: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node_modules
        id: cache-modules-docs
        uses: actions/cache@v2
        with:
          path: ./docs/node_modules
          key: ${{ matrix.node-version }}-${{ runner.OS }}-build-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: ./docs
        run: yarn install

      - name: Generate
        working-directory: ./docs
        run: yarn generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/dist
